# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.10.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: anicanedeljkovic16@gmail.com
author_name: Anica
preset_name: starter
project_name: numberguess-app

